title: <p align='center'> Parth Gandhi </p>
logo: /assets/img/parth.jpg
description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/parth-gandhi-45862017/">LinkedIn</a> |
  <a href="https://github.com/Parth6288">GitHub</a>
 
  <br>  
  I'm working as Cloud Engineer at S&P global. 
  Primarily working on kubernetes and Devops.
  I have a total of 10+ years of experience.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
